name: Prepared SDK env

on:
  workflow_dispatch:
  release:
    types: [published]

concurrency: 
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build-examples:
    runs-on: ubuntu-latest
    container: nordicplayground/nrfconnect-sdk:v2.5-branch
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          cache-dependency-path: cli/go.sum
      - name: List toolchains
        run: nrfutil toolchain-manager launch --install-dir /root/ncs env && nrfutil toolchain-manager list --install-dir /root/ncs
      - name: Build
        run: cd cli && NO_SETUP_ENV=1 HOME=/root nrfutil toolchain-manager launch go -- run ./cmd/zigbee/... --config zigbee.yml firmware --workdir $(mktemp -d zgb_build.XXXXXXXXXX) build