name: Prepared SDK env

on:
  workflow_dispatch:
  release:
    types: [published]

concurrency: 
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  empty:
    runs-on: self-hosted
    steps:
      - name: Clean-up previous
        run: rm -rf ./builds/*
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          cache-dependency-path: cli/go.sum
      - name: Test
        run: cd cli && go run ./cmd/zigbee/... --config zigbee.yml firmware --workdir $(mktemp -d ./builds/zgb_build.XXXXXXXXXX) build